<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><head><META http-equiv="Content-Type" content="text/html; charset=utf-8"></head><body>







  <div style="width:100%!important;min-width:100%;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;text-align:left;line-height:19px;font-size:14px;margin:0;padding:0">
    <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;height:100%;width:100%;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0"><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td align="center" valign="top" style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:center;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0">
          <center style="width:100%;min-width:580px">
            <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:inherit;width:580px;margin:10px auto 0;padding:0"><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;position:relative;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:10px 20px 0px 0px" align="left" valign="top">
                  <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:580px;margin:0 auto;padding:0"><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0px 0px 10px" align="left" valign="top">
                        <img src="http://justindulge.in/images/logo.png" align="center" style="outline:none;text-decoration:none;width:auto;max-width:100%;float:none;clear:both;display:block;margin:0 auto"></td>
                      <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;width:0px;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0" align="left" valign="top"></td>
                    </tr></table></td>
              </tr></table><table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:inherit;width:580px;margin:0 auto;padding:0"><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0" align="left" valign="top">
                  <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;position:relative;display:block;padding:0px"><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="border-top-width:1px;border-top-color:#1fbbad;border-top-style:dashed;word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;position:relative;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0 0 0px 0px" align="left" valign="top">
                        <table style="border-top-width:1px;border-top-color:#1fbbad;border-top-style:dashed;border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:580px;background:#1fbbad;margin:0 auto;padding:0" bgcolor="#1FBBAD"><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td align="center" style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:20px 0" valign="top">
                              <center style="width:100%;min-width:580px">
                                <h2 style="text-align:center;color:#ffffff;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:bold;line-height:1.3;word-break:normal;font-size:36px;margin:0;padding:0" align="center">Hello User!</h2>
                              </center>
                            </td>
                            <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;width:0px;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0" align="left" valign="top"></td>
                          </tr><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0px 0px 10px" align="left" valign="top">
                              <center style="width:100%;min-width:580px">
                                <p style="text-align:center;color:#fff;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:21px;font-size:18px;margin:0 0 10px;padding:0 10px" align="center">You have requested to reset your password.<br>To reset your password, click on the button below and follow the instructions shown.</p>
                              </center>
                            </td>
                            <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;width:0px;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0" align="left" valign="top"></td>
                          </tr><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;position:relative;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0px 0px 10px" align="left" valign="top">
                              <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:280px;margin:0 auto;padding:0"><tbody><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0px" align="left" valign="top">
                                    <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;overflow:hidden;padding:0"><tbody><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:center;color:#ffffff;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;display:block;width:auto!important;border-radius:3px;background:#ffffff;margin:0;padding:12px 0 10px;border:1px solid #ffffff" align="center" bgcolor="#ffffff" valign="top">
                                          <a href="${verificationUrl}" style="font-weight:normal;text-transform:uppercase;color:#1fbbad;text-decoration:none;font-family:Helvetica,Arial,sans-serif;font-size:20px">RESET PASSWORD</a>
                                        </td>
                                        <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:center;width:auto!important;color:#ffffff;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;display:block;border-radius:3px;background:#fd7f35;margin:0;padding:0;border:1px solid #ffffff" align="center" bgcolor="#fd7f35" valign="top"></td>
                                      </tr></tbody></table></td>
                                  <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;width:0px;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0" align="left" valign="top"></td>
                                </tr></tbody></table></td>
                          </tr>



                          <tr style="vertical-align:top;text-align:left;padding:0" align="left"><td align="center" style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:20px 0" valign="top">
                              <center style="width:100%;min-width:580px">
                                <p style="text-align:center;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:21px;font-size:18px;margin:0 0 10px;padding:0" align="center"><a href="#0.1_" style="color:#555555;text-decoration:underline;font-weight:bold">${verificationUrl}</a></p>
                              </center>
                            </td>
                            <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;width:0px;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0" align="left" valign="top"></td>
                          </tr>


















                          </table></td>
                    </tr></table><table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;position:relative;display:block;padding:0px"><tbody><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;position:relative;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0 20px 0px 0px" align="left" valign="top">
                                    <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:580px;background:#f0f0f0;margin:0 auto;padding:0" bgcolor="#f0f0f0"><tbody><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:30px 0px 10px" align="left" valign="top">
                                                <h5 style="text-transform:uppercase;color:#5e5e5e;text-align:center;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:1.3;word-break:normal;font-size:24px;margin:0;padding:0" align="center">Why do I have to reset my password?</h5>
                                             </td>
                                             <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;width:0px;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0" align="left" valign="top"></td>
                                          </tr></tbody></table></td>
                              </tr><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;position:relative;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0 20px 0px 0px" align="left" valign="top">
                                    <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:580px;background:#f0f0f0;margin:0 auto;padding:0" bgcolor="#f0f0f0"><tbody><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:20px 10px 0" align="left" valign="top">
                                                <p style="color:#7a7a7a;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;text-align:left;line-height:21px;font-size:18px;margin:0 0 30px;padding:0" align="left">As a security best practice, Alternacare does not store your password. As such, we cannot simply send you your old password. Instead, a unique link to reset your password has been generated for you. If you did not request to reset your password, please ignore this email. The security of your account has not been affected.</p>
                                             </td>
                                             <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;width:0px;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0" align="left" valign="top"></td>
                                          </tr></tbody></table></td>
                              </tr><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;position:relative;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0 20px 0px 0px" align="left" valign="top">
                                    <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:580px;background:#f0f0f0;margin:0 auto;padding:0" bgcolor="#f0f0f0"><tbody><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="border-top-color:#a4a4a4;border-top-width:1px;border-top-style:dashed;word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:30px 0px 10px" align="left" valign="top">
                                                <h5 style="text-transform:uppercase;color:#5e5e5e;text-align:center;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:1.3;word-break:normal;font-size:24px;margin:0;padding:0" align="center">Did not request a password reset?</h5>
                                             </td>
                                             <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;width:0px;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0" align="left" valign="top"></td>
                                          </tr></tbody></table></td>
                              </tr><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;position:relative;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0 20px 0px 0px" align="left" valign="top">
                                    <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:580px;background:#f0f0f0;margin:0 auto;padding:0" bgcolor="#f0f0f0"><tbody><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:20px 10px 0" align="left" valign="top">
                                                <p style="color:#7a7a7a;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;text-align:left;line-height:21px;font-size:18px;margin:0 0 30px;padding:0" align="left">Please ignore this email if you did not request to reset your password. The security of your account has not been affected</p>
                                             </td>
                                             <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;width:0px;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0" align="left" valign="top"></td>
                                          </tr></tbody></table></td>
                              </tr></tbody></table><table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;position:relative;display:block;padding:0px"><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;position:relative;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0 20px 0px 0px" align="left" valign="top">
                        <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:580px;background:#f0f0f0;margin:0 auto;padding:0" bgcolor="#f0f0f0"><tbody><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="border-top-color:#a4a4a4;border-top-width:1px;border-top-style:dashed;word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:30px 0px 10px 10px" align="left" valign="top">
                                <p style="color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;text-align:left;line-height:21px;font-size:18px;margin:0 0 10px;padding:0" align="left">Thank you for choosing Indulge for your beauty and wellness needs. We look forward to seeing you again soon.</p>
                              </td>
                              <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;width:0px;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0" align="left" valign="top"></td>
                            </tr><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0px 0px 10px 10px" align="left" valign="top">
                                <p style="color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;text-align:left;line-height:21px;font-size:18px;margin:0;padding:0" align="left">Sincerely,</p>
                                <p style="color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:bold;text-align:left;line-height:21px;font-size:18px;margin:0 0 10px;padding:0" align="left">Team Indulge</p>
                              </td>
                              <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;width:0px;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0" align="left" valign="top"></td>
                            </tr></tbody></table></td>
                    </tr></table><table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;position:relative;display:block;padding:0px"><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;position:relative;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0 20px 0px 0px" align="left" valign="top">
                        <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:580px;margin:0 auto;padding:0"><tbody><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:30px 0px 10px" align="left" valign="top">
                                <p style="text-align:center;color:#7a7a7a;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:21px;font-size:18px;margin:0 0 3px;padding:0" align="center">If you have any questions, see our <a href="#0.1_" style="text-decoration:underline;color:#2ba6cb"> FAQ</a> section or drop us a line at</p>
                                <p style="text-align:center;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:21px;font-size:18px;margin:0 0 10px;padding:0" align="center"><a href="mailto:abc@gmail.com" style="text-decoration:underline;color:#2ba6cb" target="_blank">support@justindulge.in</a></p>
                              </td>
                              <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;width:0px;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0" align="left" valign="top"></td>
                            </tr></tbody></table></td>
                    </tr><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;position:relative;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0 0px 0px" align="left" valign="top">
                        <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;position:relative;display:block;padding:0px"><tbody><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;position:relative;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:10px 20px 0px 0px" align="left" valign="top">
                                <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:180px;margin:0 auto;padding:0"><tbody><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0px 0px 10px" align="left" valign="top">
                                        <img src="http://i.imgur.com/ad1Uswz.png" style="outline:none;text-decoration:none;width:auto;max-width:100%;float:none;clear:both;display:block;margin:0 auto" align="none"></td>
                                      <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;width:0px;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0" align="left" valign="top"></td>
                                    </tr></tbody></table></td>
                              <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;position:relative;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:10px 20px 0px 0px" align="left" valign="top">
                                <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:180px;margin:0 auto;padding:0"><tbody><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0px 0px 10px" align="left" valign="top">
                                        <img src="http://i.imgur.com/m8sLBpq.png" style="outline:none;text-decoration:none;width:auto;max-width:100%;float:none;clear:both;display:block;margin:0 auto" align="none"></td>
                                      <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;width:0px;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0" align="left" valign="top"></td>
                                    </tr></tbody></table></td>
                              <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;position:relative;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:10px 0 0px 0px" align="left" valign="top">
                                <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:180px;margin:0 auto;padding:0"><tbody><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0px 0px 10px" align="left" valign="top">
                                        <img src="http://i.imgur.com/bcPw2sa.png" style="outline:none;text-decoration:none;width:auto;max-width:100%;float:none;clear:both;display:block;margin:0 auto" align="none"></td>
                                      <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;width:0px;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0" align="left" valign="top"></td>
                                    </tr></tbody></table></td>
                            </tr></tbody></table></td>
                    </tr><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;position:relative;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:10px 0px 30px" align="left" valign="top">
                        <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:580px;margin:0 auto;padding:0"><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td align="center" style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0px 0px 10px" valign="top">
                              <center style="width:100%;min-width:580px">
                                <p style="text-align:center;color:#7a7a7a;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:21px;font-size:18px;margin:0 0 10px;padding:0" align="center">JustIndulge, Delhi, India</p>
                                <p style="text-align:center;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:21px;font-size:18px;margin:0 0 10px;padding:0" align="center"><a href="#0.1_" style="color:#2ba6cb;text-decoration:none">Terms</a> | <a href="#0.1_" style="color:#2ba6cb;text-decoration:none">Privacy</a> | <a href="#0.1_" style="color:#2ba6cb;text-decoration:none">Unsubscribe</a></p>
                              </center>
                            </td>
                            <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;width:0px;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0" align="left" valign="top"></td>
                          </tr></table></td>
                    </tr></table></td>
              </tr></table></center>
        </td>
      </tr></table></div>

</body></html>