<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><head><META http-equiv="Content-Type" content="text/html; charset=utf-8"></head><body>







  <div style="width:100%!important;min-width:100%;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;text-align:left;line-height:19px;font-size:14px;margin:0;padding:0">
    <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;height:100%;width:100%;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0"><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td align="center" valign="top" style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:center;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0">
          <center style="width:100%;min-width:580px">
            <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:inherit;width:580px;margin:10px auto 0;padding:0"><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;position:relative;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:10px 20px 0px 0px" align="left" valign="top">
                  <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:580px;margin:0 auto;padding:0"><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0px 0px 10px" align="left" valign="top">
                        <img src="http://justindulge.in/images/merchant-logo.png" align="center" style="outline:none;text-decoration:none;width:auto;max-width:100%;float:none;clear:both;display:block;margin:0 auto"></td>
                      <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;width:0px;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0" align="left" valign="top"></td>
                    </tr></table></td>
              </tr></table><table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:inherit;width:580px;margin:0 auto;padding:0"><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0" align="left" valign="top">
                  <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;position:relative;display:block;padding:0px"><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="border-top-width:1px;border-top-color:#1fbbad;border-top-style:dashed;word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;position:relative;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0 0 0px 0px" align="left" valign="top">
                        <table style="border-top-width:1px;border-top-color:#1fbbad;border-top-style:dashed;border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:580px;background:#1fbbad;margin:0 auto;padding:0" bgcolor="#9dccb8"><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td align="center" style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:20px 0" valign="top">
                              <center style="width:100%;min-width:580px">
                                <h2 style="text-align:center;color:#ffffff;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:bold;line-height:1.3;word-break:normal;font-size:36px;margin:0;padding:0" align="center">Hello Merchant!</h2>
                                <p style="text-align:center;color:#ffffff;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:21px;font-size:18px;margin:0 0 10px;padding:0" align="center">Thank you for registering on Indulge!</p>
                                <p style="text-align:center;color:#ffffff;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:21px;font-size:18px;margin:0 0 10px;padding:0" align="center">To complete your registration and activate your account, please click on the link below </p>
                                <p style="text-align:center;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:21px;font-size:18px;margin:0 0 10px;padding:0" align="center"><a href="#0.1_" style="color:#7a7a7a;text-decoration:underline;font-weight:bold">${verificationUrl}</a></p>
                                <p style="text-align:center;color:#f0f0f0;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:21px;font-size:18px;margin:0 0 10px;padding:0" align="center">If you cannot click on the link, just copy paste it into your browser</p>
                              </center>
                            </td>
                            <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;width:0px;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0" align="left" valign="top"></td>
                          </tr></table></td>
                    </tr></table><table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;position:relative;display:block;padding:0px"><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;position:relative;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0 20px 0px 0px" align="left" valign="top">
                        <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:580px;background:#f0f0f0;margin:0 auto;padding:0" bgcolor="#f0f0f0"><tbody><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:30px 0px 10px 10px" align="left" valign="top">
                                <p style="color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;text-align:left;line-height:21px;font-size:18px;margin:0 0 10px;padding:0" align="left">Thank you for choosing Indulge for your beauty and wellness needs. We look forward to seeing you again soon.</p>
                              </td>
                              <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;width:0px;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0" align="left" valign="top"></td>
                            </tr><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0px 0px 10px 10px" align="left" valign="top">
                                <p style="color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;text-align:left;line-height:21px;font-size:18px;margin:0;padding:0" align="left">Sincerely,</p>
                                <p style="color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:bold;text-align:left;line-height:21px;font-size:18px;margin:0 0 10px;padding:0" align="left">Team Indulge</p>
                              </td>
                              <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;width:0px;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0" align="left" valign="top"></td>
                            </tr></tbody></table></td>
                    </tr></table><table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;position:relative;display:block;padding:0px"><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;position:relative;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0 20px 0px 0px" align="left" valign="top">
                        <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:580px;margin:0 auto;padding:0"><tbody><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:30px 0px 10px" align="left" valign="top">
                                <p style="text-align:center;color:#7a7a7a;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:21px;font-size:18px;margin:0 0 3px;padding:0" align="center">If you have any questions, see our <a href="http://justindulge.in/html/faq.html" style="text-decoration:underline;color:#2ba6cb"> FAQ</a> section or drop us a line at</p>
                                <p style="text-align:center;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:21px;font-size:18px;margin:0 0 10px;padding:0" align="center"><a href="mailto:abc@gmail.com" style="text-decoration:underline;color:#2ba6cb" target="_blank">support@justindulge.in</a></p>
                              </td>
                              <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;width:0px;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0" align="left" valign="top"></td>
                            </tr></tbody></table></td>
                    </tr><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;position:relative;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0 0px 0px" align="left" valign="top">
                        <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;position:relative;display:block;padding:0px"><tbody><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;position:relative;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:10px 20px 0px 0px" align="left" valign="top">
                                <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:180px;margin:0 auto;padding:0"><tbody><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0px 0px 10px" align="left" valign="top">
                                        <img src="http://i.imgur.com/ad1Uswz.png" style="outline:none;text-decoration:none;width:auto;max-width:100%;float:none;clear:both;display:block;margin:0 auto" align="none"></td>
                                      <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;width:0px;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0" align="left" valign="top"></td>
                                    </tr></tbody></table></td>
                              <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;position:relative;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:10px 20px 0px 0px" align="left" valign="top">
                                <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:180px;margin:0 auto;padding:0"><tbody><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0px 0px 10px" align="left" valign="top">
                                        <img src="http://i.imgur.com/m8sLBpq.png" style="outline:none;text-decoration:none;width:auto;max-width:100%;float:none;clear:both;display:block;margin:0 auto" align="none"></td>
                                      <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;width:0px;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0" align="left" valign="top"></td>
                                    </tr></tbody></table></td>
                              <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;position:relative;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:10px 0 0px 0px" align="left" valign="top">
                                <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:180px;margin:0 auto;padding:0"><tbody><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0px 0px 10px" align="left" valign="top">
                                        <img src="http://i.imgur.com/bcPw2sa.png" style="outline:none;text-decoration:none;width:auto;max-width:100%;float:none;clear:both;display:block;margin:0 auto" align="none"></td>
                                      <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;width:0px;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0" align="left" valign="top"></td>
                                    </tr></tbody></table></td>
                            </tr></tbody></table></td>
                    </tr><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;position:relative;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:10px 0px 30px" align="left" valign="top">
                        <table style="border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:580px;margin:0 auto;padding:0"><tr style="vertical-align:top;text-align:left;padding:0" align="left"><td align="center" style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0px 0px 10px" valign="top">
                              <center style="width:100%;min-width:580px">
                                <p style="text-align:center;color:#7a7a7a;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:21px;font-size:18px;margin:0 0 10px;padding:0" align="center">JustIndulge, Delhi, India</p>
                                <p style="text-align:center;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:21px;font-size:18px;margin:0 0 10px;padding:0" align="center"><a href="#0.1_" style="color:#2ba6cb;text-decoration:none">Terms</a> | <a href="#0.1_" style="color:#2ba6cb;text-decoration:none">Privacy</a> | <a href="#0.1_" style="color:#2ba6cb;text-decoration:none">Unsubscribe</a></p>
                              </center>
                            </td>
                            <td style="word-break:break-word;border-collapse:collapse!important;vertical-align:top;text-align:left;width:0px;color:#222222;font-family:&#39;Helvetica&#39;,&#39;Arial&#39;,sans-serif;font-weight:normal;line-height:19px;font-size:14px;margin:0;padding:0" align="left" valign="top"></td>
                          </tr></table></td>
                    </tr></table></td>
              </tr></table></center>
        </td>
      </tr></table></div>

</body></html>